version: '3'
services:
  web:
    build: .
    depends_on:
      - redis
      - mysql
      - mq
    ports:
      - 8080
  redis:
    image: redis
    ports:
      - 6379
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: xuzeyu123
      MYSQL_DATABASE: nobody_db
    ports:
      - 3306:3306
  mq:
    image: rabbitmq:3.6
    ports:
      - 5672:5672
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
