version: '2'
services:
  web:
#    image: az8321550/nobody-nodejs:v8
    build: .
    depends_on:
      - redis
      - mysql
      - mq
    ports:
      - 8080:8080
  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xuzeyu123
      MYSQL_DATABASE: nobody_db
    ports:
      - 3306:3306
  mq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: xuzeyu123