version: '3'
services:
  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    volumes:
      - ./:/data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: xuzeyu123
      MYSQL_DATABASE: nobody_db
    ports:
      - 3306:3306
  mqserver:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: xuzeyu123
