version: "3"
services:
  web:
    build: .
    depends_on:
      - redis
  redis:
    image: redis
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
